apiVersion: v1
kind: ConfigMap
metadata:
  name: rtmp-nginx-config
  labels:
    app: rtmp-server
data:
  nginx.conf: |
    worker_processes auto;
    rtmp_auto_push on;
    events {}

    rtmp {
        server {
            listen 1935;
            listen [::]:1935 ipv6only=on;

            application live {
                live on;
                hls on;
                hls_path /tmp/hls;
                hls_fragment 10s;
                hls_playlist_length 5m;

                on_publish http://api-gateway-service:8080/live/start;
                on_done http://api-gateway-service:8080/live/end;
            }
        }
    }

    http {
        server {
            listen 8888;
            
            location /hls {
                types {
                    application/vnd.apple.mpegurl m3u8;
                    application/octet-stream ts;
                }
                root /tmp;
                add_header Cache-Control no-cache;
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods 'GET, OPTIONS';
                add_header Access-Control-Allow-Headers 'Range';
            
                if ($request_method = 'OPTIONS') {
                    add_header Access-Control-Allow-Origin *;
                    add_header Access-Control-Allow-Methods 'GET, OPTIONS';
                    add_header Access-Control-Allow-Headers 'Range';
                    add_header Access-Control-Max-Age 1728000;
                    add_header Content-Type 'text/plain charset=UTF-8';
                    add_header Content-Length 0;
                    return 204;
                }
            }
        }
    }

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtmp-hls-pvc
  labels:
    app: rtmp-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-server
  labels:
    app: rtmp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtmp-server
  template:
    metadata:
      labels:
        app: rtmp-server
    spec:
      containers:
        - name: rtmp-server
          image: tiangolo/nginx-rtmp:latest
          ports:
            - containerPort: 1935 
            - containerPort: 8888 
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: hls-storage
              mountPath: /tmp/hls
      volumes:
        - name: nginx-config
          configMap:
            name: rtmp-nginx-config
        - name: hls-storage
          persistentVolumeClaim:
            claimName: rtmp-hls-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: rtmp-server
  labels:
    app: rtmp-server
spec:
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
    - name: http-hls
      port: 8888
      targetPort: 8888
  selector:
    app: rtmp-server
  type: LoadBalancer

