version: '3.9'
services:
  postgres-multidb:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: paymentservicegv 
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  rtmp:
    build: ./rtmp
    network_mode: "host"
    container_name: rtmp_server
    volumes:
      - ./rtmp/hls:/tmp/hls

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
